// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const { john, peter } = require('./4-names')
const sayHi = require('./5-utils')
const alter = require('./6-alternative-flavor')
console.log(alter.items[0])
require('./7-mind-grenade')
sayHi('susan')
sayHi(john)
sayHi(peter)